// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_404 from "./routes/_404.tsx";
import * as $_app from "./routes/_app.tsx";
import * as $api_joke from "./routes/api/joke.ts";
import * as $index from "./routes/index.tsx";
import * as $platforms_instagram from "./routes/platforms/instagram.tsx";
import * as $BarChart from "./islands/BarChart.tsx";
import * as $DragAndDrop from "./islands/DragAndDrop.tsx";
import * as $LineChart from "./islands/LineChart.tsx";
import * as $instagram_classes from "./islands/instagram/classes.tsx";
import type { Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_404.tsx": $_404,
    "./routes/_app.tsx": $_app,
    "./routes/api/joke.ts": $api_joke,
    "./routes/index.tsx": $index,
    "./routes/platforms/instagram.tsx": $platforms_instagram,
  },
  islands: {
    "./islands/BarChart.tsx": $BarChart,
    "./islands/DragAndDrop.tsx": $DragAndDrop,
    "./islands/LineChart.tsx": $LineChart,
    "./islands/instagram/classes.tsx": $instagram_classes,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
